//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BondoraAssignment.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> number_of_day { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
