//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BondoraAssignment.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FromToCalculation
    {
        public int id { get; set; }
        public Nullable<int> rate_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<int> to { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Rate Rate { get; set; }
    }
}
